# Tomcat settings
server:
  port: ${TOMCAT_SERVER_PORT:8080}

# Management settings
management:
  endpoints:
    web:
      exposure:
        include: "*"

# Logging settings
logging:
  level:
    root: WARN
    org:
      springframework:
        security: INFO
        web: ERROR
      hibernate: INFO
    com:
      incarcloud: DEBUG
  file:
    path: ${LOGGING_FILE_PATH:./}
    name: output.log
    max-size: ${LOGGING_FILE_MAX_SIZE:20MB}

# Spring settings
spring:
  profiles:
    active: dev
  application:
    name: grpc-server

# InCarCloud settings
incarcloud:
  hbase:
    zookeeper:
      quorum: ${HBASE_ZOOKEEPER_QUORUM:127.0.0.1}
      property:
        clientPort: ${HBASE_ZOOKEEPER_CLIENT_PORT:2181}
    master: ${HBASE_MASTER:127.0.0.1:60000}
    table:
      test: ${HBASE_TABLE_TEST:test}
