// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Position.proto

package com.incarcloud.grpc.proto;

public final class Position {
  private Position() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface PositionParamOrBuilder extends
      // @@protoc_insertion_point(interface_extends:PositionParam)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string vin = 1;</code>
     * @return The vin.
     */
    java.lang.String getVin();
    /**
     * <code>string vin = 1;</code>
     * @return The bytes for vin.
     */
    com.google.protobuf.ByteString
        getVinBytes();
  }
  /**
   * Protobuf type {@code PositionParam}
   */
  public  static final class PositionParam extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:PositionParam)
      PositionParamOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use PositionParam.newBuilder() to construct.
    private PositionParam(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private PositionParam() {
      vin_ = "";
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new PositionParam();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private PositionParam(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();

              vin_ = s;
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.incarcloud.grpc.proto.Position.internal_static_PositionParam_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.incarcloud.grpc.proto.Position.internal_static_PositionParam_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.incarcloud.grpc.proto.Position.PositionParam.class, com.incarcloud.grpc.proto.Position.PositionParam.Builder.class);
    }

    public static final int VIN_FIELD_NUMBER = 1;
    private volatile java.lang.Object vin_;
    /**
     * <code>string vin = 1;</code>
     * @return The vin.
     */
    public java.lang.String getVin() {
      java.lang.Object ref = vin_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        vin_ = s;
        return s;
      }
    }
    /**
     * <code>string vin = 1;</code>
     * @return The bytes for vin.
     */
    public com.google.protobuf.ByteString
        getVinBytes() {
      java.lang.Object ref = vin_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        vin_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!getVinBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, vin_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getVinBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, vin_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.incarcloud.grpc.proto.Position.PositionParam)) {
        return super.equals(obj);
      }
      com.incarcloud.grpc.proto.Position.PositionParam other = (com.incarcloud.grpc.proto.Position.PositionParam) obj;

      if (!getVin()
          .equals(other.getVin())) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + VIN_FIELD_NUMBER;
      hash = (53 * hash) + getVin().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.incarcloud.grpc.proto.Position.PositionParam parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.incarcloud.grpc.proto.Position.PositionParam parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.incarcloud.grpc.proto.Position.PositionParam parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.incarcloud.grpc.proto.Position.PositionParam parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.incarcloud.grpc.proto.Position.PositionParam parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.incarcloud.grpc.proto.Position.PositionParam parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.incarcloud.grpc.proto.Position.PositionParam parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.incarcloud.grpc.proto.Position.PositionParam parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.incarcloud.grpc.proto.Position.PositionParam parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.incarcloud.grpc.proto.Position.PositionParam parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.incarcloud.grpc.proto.Position.PositionParam parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.incarcloud.grpc.proto.Position.PositionParam parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.incarcloud.grpc.proto.Position.PositionParam prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code PositionParam}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:PositionParam)
        com.incarcloud.grpc.proto.Position.PositionParamOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.incarcloud.grpc.proto.Position.internal_static_PositionParam_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.incarcloud.grpc.proto.Position.internal_static_PositionParam_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.incarcloud.grpc.proto.Position.PositionParam.class, com.incarcloud.grpc.proto.Position.PositionParam.Builder.class);
      }

      // Construct using com.incarcloud.grpc.proto.Position.PositionParam.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        vin_ = "";

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.incarcloud.grpc.proto.Position.internal_static_PositionParam_descriptor;
      }

      @java.lang.Override
      public com.incarcloud.grpc.proto.Position.PositionParam getDefaultInstanceForType() {
        return com.incarcloud.grpc.proto.Position.PositionParam.getDefaultInstance();
      }

      @java.lang.Override
      public com.incarcloud.grpc.proto.Position.PositionParam build() {
        com.incarcloud.grpc.proto.Position.PositionParam result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.incarcloud.grpc.proto.Position.PositionParam buildPartial() {
        com.incarcloud.grpc.proto.Position.PositionParam result = new com.incarcloud.grpc.proto.Position.PositionParam(this);
        result.vin_ = vin_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.incarcloud.grpc.proto.Position.PositionParam) {
          return mergeFrom((com.incarcloud.grpc.proto.Position.PositionParam)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.incarcloud.grpc.proto.Position.PositionParam other) {
        if (other == com.incarcloud.grpc.proto.Position.PositionParam.getDefaultInstance()) return this;
        if (!other.getVin().isEmpty()) {
          vin_ = other.vin_;
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.incarcloud.grpc.proto.Position.PositionParam parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.incarcloud.grpc.proto.Position.PositionParam) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private java.lang.Object vin_ = "";
      /**
       * <code>string vin = 1;</code>
       * @return The vin.
       */
      public java.lang.String getVin() {
        java.lang.Object ref = vin_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          vin_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string vin = 1;</code>
       * @return The bytes for vin.
       */
      public com.google.protobuf.ByteString
          getVinBytes() {
        java.lang.Object ref = vin_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          vin_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string vin = 1;</code>
       * @param value The vin to set.
       * @return This builder for chaining.
       */
      public Builder setVin(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        vin_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string vin = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearVin() {
        
        vin_ = getDefaultInstance().getVin();
        onChanged();
        return this;
      }
      /**
       * <code>string vin = 1;</code>
       * @param value The bytes for vin to set.
       * @return This builder for chaining.
       */
      public Builder setVinBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        vin_ = value;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:PositionParam)
    }

    // @@protoc_insertion_point(class_scope:PositionParam)
    private static final com.incarcloud.grpc.proto.Position.PositionParam DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.incarcloud.grpc.proto.Position.PositionParam();
    }

    public static com.incarcloud.grpc.proto.Position.PositionParam getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<PositionParam>
        PARSER = new com.google.protobuf.AbstractParser<PositionParam>() {
      @java.lang.Override
      public PositionParam parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new PositionParam(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<PositionParam> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<PositionParam> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.incarcloud.grpc.proto.Position.PositionParam getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface PositionDataOrBuilder extends
      // @@protoc_insertion_point(interface_extends:PositionData)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string vin = 1;</code>
     * @return The vin.
     */
    java.lang.String getVin();
    /**
     * <code>string vin = 1;</code>
     * @return The bytes for vin.
     */
    com.google.protobuf.ByteString
        getVinBytes();

    /**
     * <code>double longitude = 2;</code>
     * @return The longitude.
     */
    double getLongitude();

    /**
     * <code>double latitude = 3;</code>
     * @return The latitude.
     */
    double getLatitude();
  }
  /**
   * Protobuf type {@code PositionData}
   */
  public  static final class PositionData extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:PositionData)
      PositionDataOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use PositionData.newBuilder() to construct.
    private PositionData(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private PositionData() {
      vin_ = "";
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new PositionData();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private PositionData(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();

              vin_ = s;
              break;
            }
            case 17: {

              longitude_ = input.readDouble();
              break;
            }
            case 25: {

              latitude_ = input.readDouble();
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.incarcloud.grpc.proto.Position.internal_static_PositionData_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.incarcloud.grpc.proto.Position.internal_static_PositionData_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.incarcloud.grpc.proto.Position.PositionData.class, com.incarcloud.grpc.proto.Position.PositionData.Builder.class);
    }

    public static final int VIN_FIELD_NUMBER = 1;
    private volatile java.lang.Object vin_;
    /**
     * <code>string vin = 1;</code>
     * @return The vin.
     */
    public java.lang.String getVin() {
      java.lang.Object ref = vin_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        vin_ = s;
        return s;
      }
    }
    /**
     * <code>string vin = 1;</code>
     * @return The bytes for vin.
     */
    public com.google.protobuf.ByteString
        getVinBytes() {
      java.lang.Object ref = vin_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        vin_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int LONGITUDE_FIELD_NUMBER = 2;
    private double longitude_;
    /**
     * <code>double longitude = 2;</code>
     * @return The longitude.
     */
    public double getLongitude() {
      return longitude_;
    }

    public static final int LATITUDE_FIELD_NUMBER = 3;
    private double latitude_;
    /**
     * <code>double latitude = 3;</code>
     * @return The latitude.
     */
    public double getLatitude() {
      return latitude_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!getVinBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, vin_);
      }
      if (longitude_ != 0D) {
        output.writeDouble(2, longitude_);
      }
      if (latitude_ != 0D) {
        output.writeDouble(3, latitude_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getVinBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, vin_);
      }
      if (longitude_ != 0D) {
        size += com.google.protobuf.CodedOutputStream
          .computeDoubleSize(2, longitude_);
      }
      if (latitude_ != 0D) {
        size += com.google.protobuf.CodedOutputStream
          .computeDoubleSize(3, latitude_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.incarcloud.grpc.proto.Position.PositionData)) {
        return super.equals(obj);
      }
      com.incarcloud.grpc.proto.Position.PositionData other = (com.incarcloud.grpc.proto.Position.PositionData) obj;

      if (!getVin()
          .equals(other.getVin())) return false;
      if (java.lang.Double.doubleToLongBits(getLongitude())
          != java.lang.Double.doubleToLongBits(
              other.getLongitude())) return false;
      if (java.lang.Double.doubleToLongBits(getLatitude())
          != java.lang.Double.doubleToLongBits(
              other.getLatitude())) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + VIN_FIELD_NUMBER;
      hash = (53 * hash) + getVin().hashCode();
      hash = (37 * hash) + LONGITUDE_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          java.lang.Double.doubleToLongBits(getLongitude()));
      hash = (37 * hash) + LATITUDE_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          java.lang.Double.doubleToLongBits(getLatitude()));
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.incarcloud.grpc.proto.Position.PositionData parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.incarcloud.grpc.proto.Position.PositionData parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.incarcloud.grpc.proto.Position.PositionData parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.incarcloud.grpc.proto.Position.PositionData parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.incarcloud.grpc.proto.Position.PositionData parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.incarcloud.grpc.proto.Position.PositionData parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.incarcloud.grpc.proto.Position.PositionData parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.incarcloud.grpc.proto.Position.PositionData parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.incarcloud.grpc.proto.Position.PositionData parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.incarcloud.grpc.proto.Position.PositionData parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.incarcloud.grpc.proto.Position.PositionData parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.incarcloud.grpc.proto.Position.PositionData parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.incarcloud.grpc.proto.Position.PositionData prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code PositionData}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:PositionData)
        com.incarcloud.grpc.proto.Position.PositionDataOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.incarcloud.grpc.proto.Position.internal_static_PositionData_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.incarcloud.grpc.proto.Position.internal_static_PositionData_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.incarcloud.grpc.proto.Position.PositionData.class, com.incarcloud.grpc.proto.Position.PositionData.Builder.class);
      }

      // Construct using com.incarcloud.grpc.proto.Position.PositionData.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        vin_ = "";

        longitude_ = 0D;

        latitude_ = 0D;

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.incarcloud.grpc.proto.Position.internal_static_PositionData_descriptor;
      }

      @java.lang.Override
      public com.incarcloud.grpc.proto.Position.PositionData getDefaultInstanceForType() {
        return com.incarcloud.grpc.proto.Position.PositionData.getDefaultInstance();
      }

      @java.lang.Override
      public com.incarcloud.grpc.proto.Position.PositionData build() {
        com.incarcloud.grpc.proto.Position.PositionData result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.incarcloud.grpc.proto.Position.PositionData buildPartial() {
        com.incarcloud.grpc.proto.Position.PositionData result = new com.incarcloud.grpc.proto.Position.PositionData(this);
        result.vin_ = vin_;
        result.longitude_ = longitude_;
        result.latitude_ = latitude_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.incarcloud.grpc.proto.Position.PositionData) {
          return mergeFrom((com.incarcloud.grpc.proto.Position.PositionData)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.incarcloud.grpc.proto.Position.PositionData other) {
        if (other == com.incarcloud.grpc.proto.Position.PositionData.getDefaultInstance()) return this;
        if (!other.getVin().isEmpty()) {
          vin_ = other.vin_;
          onChanged();
        }
        if (other.getLongitude() != 0D) {
          setLongitude(other.getLongitude());
        }
        if (other.getLatitude() != 0D) {
          setLatitude(other.getLatitude());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.incarcloud.grpc.proto.Position.PositionData parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.incarcloud.grpc.proto.Position.PositionData) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private java.lang.Object vin_ = "";
      /**
       * <code>string vin = 1;</code>
       * @return The vin.
       */
      public java.lang.String getVin() {
        java.lang.Object ref = vin_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          vin_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string vin = 1;</code>
       * @return The bytes for vin.
       */
      public com.google.protobuf.ByteString
          getVinBytes() {
        java.lang.Object ref = vin_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          vin_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string vin = 1;</code>
       * @param value The vin to set.
       * @return This builder for chaining.
       */
      public Builder setVin(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        vin_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string vin = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearVin() {
        
        vin_ = getDefaultInstance().getVin();
        onChanged();
        return this;
      }
      /**
       * <code>string vin = 1;</code>
       * @param value The bytes for vin to set.
       * @return This builder for chaining.
       */
      public Builder setVinBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        vin_ = value;
        onChanged();
        return this;
      }

      private double longitude_ ;
      /**
       * <code>double longitude = 2;</code>
       * @return The longitude.
       */
      public double getLongitude() {
        return longitude_;
      }
      /**
       * <code>double longitude = 2;</code>
       * @param value The longitude to set.
       * @return This builder for chaining.
       */
      public Builder setLongitude(double value) {
        
        longitude_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>double longitude = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearLongitude() {
        
        longitude_ = 0D;
        onChanged();
        return this;
      }

      private double latitude_ ;
      /**
       * <code>double latitude = 3;</code>
       * @return The latitude.
       */
      public double getLatitude() {
        return latitude_;
      }
      /**
       * <code>double latitude = 3;</code>
       * @param value The latitude to set.
       * @return This builder for chaining.
       */
      public Builder setLatitude(double value) {
        
        latitude_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>double latitude = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearLatitude() {
        
        latitude_ = 0D;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:PositionData)
    }

    // @@protoc_insertion_point(class_scope:PositionData)
    private static final com.incarcloud.grpc.proto.Position.PositionData DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.incarcloud.grpc.proto.Position.PositionData();
    }

    public static com.incarcloud.grpc.proto.Position.PositionData getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<PositionData>
        PARSER = new com.google.protobuf.AbstractParser<PositionData>() {
      @java.lang.Override
      public PositionData parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new PositionData(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<PositionData> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<PositionData> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.incarcloud.grpc.proto.Position.PositionData getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface PositionDataListOrBuilder extends
      // @@protoc_insertion_point(interface_extends:PositionDataList)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>repeated .PositionData positionData = 1;</code>
     */
    java.util.List<com.incarcloud.grpc.proto.Position.PositionData> 
        getPositionDataList();
    /**
     * <code>repeated .PositionData positionData = 1;</code>
     */
    com.incarcloud.grpc.proto.Position.PositionData getPositionData(int index);
    /**
     * <code>repeated .PositionData positionData = 1;</code>
     */
    int getPositionDataCount();
    /**
     * <code>repeated .PositionData positionData = 1;</code>
     */
    java.util.List<? extends com.incarcloud.grpc.proto.Position.PositionDataOrBuilder> 
        getPositionDataOrBuilderList();
    /**
     * <code>repeated .PositionData positionData = 1;</code>
     */
    com.incarcloud.grpc.proto.Position.PositionDataOrBuilder getPositionDataOrBuilder(
        int index);
  }
  /**
   * Protobuf type {@code PositionDataList}
   */
  public  static final class PositionDataList extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:PositionDataList)
      PositionDataListOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use PositionDataList.newBuilder() to construct.
    private PositionDataList(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private PositionDataList() {
      positionData_ = java.util.Collections.emptyList();
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new PositionDataList();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private PositionDataList(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              if (!((mutable_bitField0_ & 0x00000001) != 0)) {
                positionData_ = new java.util.ArrayList<com.incarcloud.grpc.proto.Position.PositionData>();
                mutable_bitField0_ |= 0x00000001;
              }
              positionData_.add(
                  input.readMessage(com.incarcloud.grpc.proto.Position.PositionData.parser(), extensionRegistry));
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000001) != 0)) {
          positionData_ = java.util.Collections.unmodifiableList(positionData_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.incarcloud.grpc.proto.Position.internal_static_PositionDataList_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.incarcloud.grpc.proto.Position.internal_static_PositionDataList_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.incarcloud.grpc.proto.Position.PositionDataList.class, com.incarcloud.grpc.proto.Position.PositionDataList.Builder.class);
    }

    public static final int POSITIONDATA_FIELD_NUMBER = 1;
    private java.util.List<com.incarcloud.grpc.proto.Position.PositionData> positionData_;
    /**
     * <code>repeated .PositionData positionData = 1;</code>
     */
    public java.util.List<com.incarcloud.grpc.proto.Position.PositionData> getPositionDataList() {
      return positionData_;
    }
    /**
     * <code>repeated .PositionData positionData = 1;</code>
     */
    public java.util.List<? extends com.incarcloud.grpc.proto.Position.PositionDataOrBuilder> 
        getPositionDataOrBuilderList() {
      return positionData_;
    }
    /**
     * <code>repeated .PositionData positionData = 1;</code>
     */
    public int getPositionDataCount() {
      return positionData_.size();
    }
    /**
     * <code>repeated .PositionData positionData = 1;</code>
     */
    public com.incarcloud.grpc.proto.Position.PositionData getPositionData(int index) {
      return positionData_.get(index);
    }
    /**
     * <code>repeated .PositionData positionData = 1;</code>
     */
    public com.incarcloud.grpc.proto.Position.PositionDataOrBuilder getPositionDataOrBuilder(
        int index) {
      return positionData_.get(index);
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      for (int i = 0; i < positionData_.size(); i++) {
        output.writeMessage(1, positionData_.get(i));
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      for (int i = 0; i < positionData_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, positionData_.get(i));
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.incarcloud.grpc.proto.Position.PositionDataList)) {
        return super.equals(obj);
      }
      com.incarcloud.grpc.proto.Position.PositionDataList other = (com.incarcloud.grpc.proto.Position.PositionDataList) obj;

      if (!getPositionDataList()
          .equals(other.getPositionDataList())) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (getPositionDataCount() > 0) {
        hash = (37 * hash) + POSITIONDATA_FIELD_NUMBER;
        hash = (53 * hash) + getPositionDataList().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.incarcloud.grpc.proto.Position.PositionDataList parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.incarcloud.grpc.proto.Position.PositionDataList parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.incarcloud.grpc.proto.Position.PositionDataList parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.incarcloud.grpc.proto.Position.PositionDataList parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.incarcloud.grpc.proto.Position.PositionDataList parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.incarcloud.grpc.proto.Position.PositionDataList parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.incarcloud.grpc.proto.Position.PositionDataList parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.incarcloud.grpc.proto.Position.PositionDataList parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.incarcloud.grpc.proto.Position.PositionDataList parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.incarcloud.grpc.proto.Position.PositionDataList parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.incarcloud.grpc.proto.Position.PositionDataList parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.incarcloud.grpc.proto.Position.PositionDataList parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.incarcloud.grpc.proto.Position.PositionDataList prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code PositionDataList}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:PositionDataList)
        com.incarcloud.grpc.proto.Position.PositionDataListOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.incarcloud.grpc.proto.Position.internal_static_PositionDataList_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.incarcloud.grpc.proto.Position.internal_static_PositionDataList_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.incarcloud.grpc.proto.Position.PositionDataList.class, com.incarcloud.grpc.proto.Position.PositionDataList.Builder.class);
      }

      // Construct using com.incarcloud.grpc.proto.Position.PositionDataList.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
          getPositionDataFieldBuilder();
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        if (positionDataBuilder_ == null) {
          positionData_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
        } else {
          positionDataBuilder_.clear();
        }
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.incarcloud.grpc.proto.Position.internal_static_PositionDataList_descriptor;
      }

      @java.lang.Override
      public com.incarcloud.grpc.proto.Position.PositionDataList getDefaultInstanceForType() {
        return com.incarcloud.grpc.proto.Position.PositionDataList.getDefaultInstance();
      }

      @java.lang.Override
      public com.incarcloud.grpc.proto.Position.PositionDataList build() {
        com.incarcloud.grpc.proto.Position.PositionDataList result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.incarcloud.grpc.proto.Position.PositionDataList buildPartial() {
        com.incarcloud.grpc.proto.Position.PositionDataList result = new com.incarcloud.grpc.proto.Position.PositionDataList(this);
        int from_bitField0_ = bitField0_;
        if (positionDataBuilder_ == null) {
          if (((bitField0_ & 0x00000001) != 0)) {
            positionData_ = java.util.Collections.unmodifiableList(positionData_);
            bitField0_ = (bitField0_ & ~0x00000001);
          }
          result.positionData_ = positionData_;
        } else {
          result.positionData_ = positionDataBuilder_.build();
        }
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.incarcloud.grpc.proto.Position.PositionDataList) {
          return mergeFrom((com.incarcloud.grpc.proto.Position.PositionDataList)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.incarcloud.grpc.proto.Position.PositionDataList other) {
        if (other == com.incarcloud.grpc.proto.Position.PositionDataList.getDefaultInstance()) return this;
        if (positionDataBuilder_ == null) {
          if (!other.positionData_.isEmpty()) {
            if (positionData_.isEmpty()) {
              positionData_ = other.positionData_;
              bitField0_ = (bitField0_ & ~0x00000001);
            } else {
              ensurePositionDataIsMutable();
              positionData_.addAll(other.positionData_);
            }
            onChanged();
          }
        } else {
          if (!other.positionData_.isEmpty()) {
            if (positionDataBuilder_.isEmpty()) {
              positionDataBuilder_.dispose();
              positionDataBuilder_ = null;
              positionData_ = other.positionData_;
              bitField0_ = (bitField0_ & ~0x00000001);
              positionDataBuilder_ = 
                com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                   getPositionDataFieldBuilder() : null;
            } else {
              positionDataBuilder_.addAllMessages(other.positionData_);
            }
          }
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.incarcloud.grpc.proto.Position.PositionDataList parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.incarcloud.grpc.proto.Position.PositionDataList) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.util.List<com.incarcloud.grpc.proto.Position.PositionData> positionData_ =
        java.util.Collections.emptyList();
      private void ensurePositionDataIsMutable() {
        if (!((bitField0_ & 0x00000001) != 0)) {
          positionData_ = new java.util.ArrayList<com.incarcloud.grpc.proto.Position.PositionData>(positionData_);
          bitField0_ |= 0x00000001;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilderV3<
          com.incarcloud.grpc.proto.Position.PositionData, com.incarcloud.grpc.proto.Position.PositionData.Builder, com.incarcloud.grpc.proto.Position.PositionDataOrBuilder> positionDataBuilder_;

      /**
       * <code>repeated .PositionData positionData = 1;</code>
       */
      public java.util.List<com.incarcloud.grpc.proto.Position.PositionData> getPositionDataList() {
        if (positionDataBuilder_ == null) {
          return java.util.Collections.unmodifiableList(positionData_);
        } else {
          return positionDataBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .PositionData positionData = 1;</code>
       */
      public int getPositionDataCount() {
        if (positionDataBuilder_ == null) {
          return positionData_.size();
        } else {
          return positionDataBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .PositionData positionData = 1;</code>
       */
      public com.incarcloud.grpc.proto.Position.PositionData getPositionData(int index) {
        if (positionDataBuilder_ == null) {
          return positionData_.get(index);
        } else {
          return positionDataBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .PositionData positionData = 1;</code>
       */
      public Builder setPositionData(
          int index, com.incarcloud.grpc.proto.Position.PositionData value) {
        if (positionDataBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensurePositionDataIsMutable();
          positionData_.set(index, value);
          onChanged();
        } else {
          positionDataBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .PositionData positionData = 1;</code>
       */
      public Builder setPositionData(
          int index, com.incarcloud.grpc.proto.Position.PositionData.Builder builderForValue) {
        if (positionDataBuilder_ == null) {
          ensurePositionDataIsMutable();
          positionData_.set(index, builderForValue.build());
          onChanged();
        } else {
          positionDataBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .PositionData positionData = 1;</code>
       */
      public Builder addPositionData(com.incarcloud.grpc.proto.Position.PositionData value) {
        if (positionDataBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensurePositionDataIsMutable();
          positionData_.add(value);
          onChanged();
        } else {
          positionDataBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .PositionData positionData = 1;</code>
       */
      public Builder addPositionData(
          int index, com.incarcloud.grpc.proto.Position.PositionData value) {
        if (positionDataBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensurePositionDataIsMutable();
          positionData_.add(index, value);
          onChanged();
        } else {
          positionDataBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .PositionData positionData = 1;</code>
       */
      public Builder addPositionData(
          com.incarcloud.grpc.proto.Position.PositionData.Builder builderForValue) {
        if (positionDataBuilder_ == null) {
          ensurePositionDataIsMutable();
          positionData_.add(builderForValue.build());
          onChanged();
        } else {
          positionDataBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .PositionData positionData = 1;</code>
       */
      public Builder addPositionData(
          int index, com.incarcloud.grpc.proto.Position.PositionData.Builder builderForValue) {
        if (positionDataBuilder_ == null) {
          ensurePositionDataIsMutable();
          positionData_.add(index, builderForValue.build());
          onChanged();
        } else {
          positionDataBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .PositionData positionData = 1;</code>
       */
      public Builder addAllPositionData(
          java.lang.Iterable<? extends com.incarcloud.grpc.proto.Position.PositionData> values) {
        if (positionDataBuilder_ == null) {
          ensurePositionDataIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, positionData_);
          onChanged();
        } else {
          positionDataBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .PositionData positionData = 1;</code>
       */
      public Builder clearPositionData() {
        if (positionDataBuilder_ == null) {
          positionData_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
          onChanged();
        } else {
          positionDataBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .PositionData positionData = 1;</code>
       */
      public Builder removePositionData(int index) {
        if (positionDataBuilder_ == null) {
          ensurePositionDataIsMutable();
          positionData_.remove(index);
          onChanged();
        } else {
          positionDataBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .PositionData positionData = 1;</code>
       */
      public com.incarcloud.grpc.proto.Position.PositionData.Builder getPositionDataBuilder(
          int index) {
        return getPositionDataFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .PositionData positionData = 1;</code>
       */
      public com.incarcloud.grpc.proto.Position.PositionDataOrBuilder getPositionDataOrBuilder(
          int index) {
        if (positionDataBuilder_ == null) {
          return positionData_.get(index);  } else {
          return positionDataBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .PositionData positionData = 1;</code>
       */
      public java.util.List<? extends com.incarcloud.grpc.proto.Position.PositionDataOrBuilder> 
           getPositionDataOrBuilderList() {
        if (positionDataBuilder_ != null) {
          return positionDataBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(positionData_);
        }
      }
      /**
       * <code>repeated .PositionData positionData = 1;</code>
       */
      public com.incarcloud.grpc.proto.Position.PositionData.Builder addPositionDataBuilder() {
        return getPositionDataFieldBuilder().addBuilder(
            com.incarcloud.grpc.proto.Position.PositionData.getDefaultInstance());
      }
      /**
       * <code>repeated .PositionData positionData = 1;</code>
       */
      public com.incarcloud.grpc.proto.Position.PositionData.Builder addPositionDataBuilder(
          int index) {
        return getPositionDataFieldBuilder().addBuilder(
            index, com.incarcloud.grpc.proto.Position.PositionData.getDefaultInstance());
      }
      /**
       * <code>repeated .PositionData positionData = 1;</code>
       */
      public java.util.List<com.incarcloud.grpc.proto.Position.PositionData.Builder> 
           getPositionDataBuilderList() {
        return getPositionDataFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilderV3<
          com.incarcloud.grpc.proto.Position.PositionData, com.incarcloud.grpc.proto.Position.PositionData.Builder, com.incarcloud.grpc.proto.Position.PositionDataOrBuilder> 
          getPositionDataFieldBuilder() {
        if (positionDataBuilder_ == null) {
          positionDataBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
              com.incarcloud.grpc.proto.Position.PositionData, com.incarcloud.grpc.proto.Position.PositionData.Builder, com.incarcloud.grpc.proto.Position.PositionDataOrBuilder>(
                  positionData_,
                  ((bitField0_ & 0x00000001) != 0),
                  getParentForChildren(),
                  isClean());
          positionData_ = null;
        }
        return positionDataBuilder_;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:PositionDataList)
    }

    // @@protoc_insertion_point(class_scope:PositionDataList)
    private static final com.incarcloud.grpc.proto.Position.PositionDataList DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.incarcloud.grpc.proto.Position.PositionDataList();
    }

    public static com.incarcloud.grpc.proto.Position.PositionDataList getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<PositionDataList>
        PARSER = new com.google.protobuf.AbstractParser<PositionDataList>() {
      @java.lang.Override
      public PositionDataList parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new PositionDataList(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<PositionDataList> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<PositionDataList> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.incarcloud.grpc.proto.Position.PositionDataList getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_PositionParam_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_PositionParam_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_PositionData_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_PositionData_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_PositionDataList_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_PositionDataList_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\016Position.proto\"\034\n\rPositionParam\022\013\n\003vin" +
      "\030\001 \001(\t\"@\n\014PositionData\022\013\n\003vin\030\001 \001(\t\022\021\n\tl" +
      "ongitude\030\002 \001(\001\022\020\n\010latitude\030\003 \001(\001\"7\n\020Posi" +
      "tionDataList\022#\n\014positionData\030\001 \003(\0132\r.Pos" +
      "itionData2A\n\017PositionService\022.\n\tqueryLis" +
      "t\022\016.PositionParam\032\021.PositionDataListB%\n\031" +
      "com.incarcloud.grpc.protoB\010Positionb\006pro" +
      "to3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_PositionParam_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_PositionParam_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_PositionParam_descriptor,
        new java.lang.String[] { "Vin", });
    internal_static_PositionData_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_PositionData_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_PositionData_descriptor,
        new java.lang.String[] { "Vin", "Longitude", "Latitude", });
    internal_static_PositionDataList_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_PositionDataList_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_PositionDataList_descriptor,
        new java.lang.String[] { "PositionData", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
