// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Simple.proto

package com.incarcloud.grpc.proto;

public final class Simple {
  private Simple() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface SimpleParamOrBuilder extends
      // @@protoc_insertion_point(interface_extends:simple.SimpleParam)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string vin = 1;</code>
     * @return The vin.
     */
    java.lang.String getVin();
    /**
     * <code>string vin = 1;</code>
     * @return The bytes for vin.
     */
    com.google.protobuf.ByteString
        getVinBytes();
  }
  /**
   * Protobuf type {@code simple.SimpleParam}
   */
  public  static final class SimpleParam extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:simple.SimpleParam)
      SimpleParamOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use SimpleParam.newBuilder() to construct.
    private SimpleParam(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private SimpleParam() {
      vin_ = "";
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new SimpleParam();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private SimpleParam(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();

              vin_ = s;
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.incarcloud.grpc.proto.Simple.internal_static_simple_SimpleParam_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.incarcloud.grpc.proto.Simple.internal_static_simple_SimpleParam_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.incarcloud.grpc.proto.Simple.SimpleParam.class, com.incarcloud.grpc.proto.Simple.SimpleParam.Builder.class);
    }

    public static final int VIN_FIELD_NUMBER = 1;
    private volatile java.lang.Object vin_;
    /**
     * <code>string vin = 1;</code>
     * @return The vin.
     */
    public java.lang.String getVin() {
      java.lang.Object ref = vin_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        vin_ = s;
        return s;
      }
    }
    /**
     * <code>string vin = 1;</code>
     * @return The bytes for vin.
     */
    public com.google.protobuf.ByteString
        getVinBytes() {
      java.lang.Object ref = vin_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        vin_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!getVinBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, vin_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getVinBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, vin_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.incarcloud.grpc.proto.Simple.SimpleParam)) {
        return super.equals(obj);
      }
      com.incarcloud.grpc.proto.Simple.SimpleParam other = (com.incarcloud.grpc.proto.Simple.SimpleParam) obj;

      if (!getVin()
          .equals(other.getVin())) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + VIN_FIELD_NUMBER;
      hash = (53 * hash) + getVin().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.incarcloud.grpc.proto.Simple.SimpleParam parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.incarcloud.grpc.proto.Simple.SimpleParam parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.incarcloud.grpc.proto.Simple.SimpleParam parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.incarcloud.grpc.proto.Simple.SimpleParam parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.incarcloud.grpc.proto.Simple.SimpleParam parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.incarcloud.grpc.proto.Simple.SimpleParam parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.incarcloud.grpc.proto.Simple.SimpleParam parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.incarcloud.grpc.proto.Simple.SimpleParam parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.incarcloud.grpc.proto.Simple.SimpleParam parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.incarcloud.grpc.proto.Simple.SimpleParam parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.incarcloud.grpc.proto.Simple.SimpleParam parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.incarcloud.grpc.proto.Simple.SimpleParam parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.incarcloud.grpc.proto.Simple.SimpleParam prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code simple.SimpleParam}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:simple.SimpleParam)
        com.incarcloud.grpc.proto.Simple.SimpleParamOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.incarcloud.grpc.proto.Simple.internal_static_simple_SimpleParam_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.incarcloud.grpc.proto.Simple.internal_static_simple_SimpleParam_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.incarcloud.grpc.proto.Simple.SimpleParam.class, com.incarcloud.grpc.proto.Simple.SimpleParam.Builder.class);
      }

      // Construct using com.incarcloud.grpc.proto.Simple.SimpleParam.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        vin_ = "";

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.incarcloud.grpc.proto.Simple.internal_static_simple_SimpleParam_descriptor;
      }

      @java.lang.Override
      public com.incarcloud.grpc.proto.Simple.SimpleParam getDefaultInstanceForType() {
        return com.incarcloud.grpc.proto.Simple.SimpleParam.getDefaultInstance();
      }

      @java.lang.Override
      public com.incarcloud.grpc.proto.Simple.SimpleParam build() {
        com.incarcloud.grpc.proto.Simple.SimpleParam result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.incarcloud.grpc.proto.Simple.SimpleParam buildPartial() {
        com.incarcloud.grpc.proto.Simple.SimpleParam result = new com.incarcloud.grpc.proto.Simple.SimpleParam(this);
        result.vin_ = vin_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.incarcloud.grpc.proto.Simple.SimpleParam) {
          return mergeFrom((com.incarcloud.grpc.proto.Simple.SimpleParam)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.incarcloud.grpc.proto.Simple.SimpleParam other) {
        if (other == com.incarcloud.grpc.proto.Simple.SimpleParam.getDefaultInstance()) return this;
        if (!other.getVin().isEmpty()) {
          vin_ = other.vin_;
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.incarcloud.grpc.proto.Simple.SimpleParam parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.incarcloud.grpc.proto.Simple.SimpleParam) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private java.lang.Object vin_ = "";
      /**
       * <code>string vin = 1;</code>
       * @return The vin.
       */
      public java.lang.String getVin() {
        java.lang.Object ref = vin_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          vin_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string vin = 1;</code>
       * @return The bytes for vin.
       */
      public com.google.protobuf.ByteString
          getVinBytes() {
        java.lang.Object ref = vin_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          vin_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string vin = 1;</code>
       * @param value The vin to set.
       * @return This builder for chaining.
       */
      public Builder setVin(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        vin_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string vin = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearVin() {
        
        vin_ = getDefaultInstance().getVin();
        onChanged();
        return this;
      }
      /**
       * <code>string vin = 1;</code>
       * @param value The bytes for vin to set.
       * @return This builder for chaining.
       */
      public Builder setVinBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        vin_ = value;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:simple.SimpleParam)
    }

    // @@protoc_insertion_point(class_scope:simple.SimpleParam)
    private static final com.incarcloud.grpc.proto.Simple.SimpleParam DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.incarcloud.grpc.proto.Simple.SimpleParam();
    }

    public static com.incarcloud.grpc.proto.Simple.SimpleParam getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<SimpleParam>
        PARSER = new com.google.protobuf.AbstractParser<SimpleParam>() {
      @java.lang.Override
      public SimpleParam parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new SimpleParam(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<SimpleParam> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<SimpleParam> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.incarcloud.grpc.proto.Simple.SimpleParam getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface SimpleDataOrBuilder extends
      // @@protoc_insertion_point(interface_extends:simple.SimpleData)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>double longitude = 1;</code>
     * @return The longitude.
     */
    double getLongitude();

    /**
     * <code>double latitude = 2;</code>
     * @return The latitude.
     */
    double getLatitude();
  }
  /**
   * Protobuf type {@code simple.SimpleData}
   */
  public  static final class SimpleData extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:simple.SimpleData)
      SimpleDataOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use SimpleData.newBuilder() to construct.
    private SimpleData(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private SimpleData() {
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new SimpleData();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private SimpleData(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 9: {

              longitude_ = input.readDouble();
              break;
            }
            case 17: {

              latitude_ = input.readDouble();
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.incarcloud.grpc.proto.Simple.internal_static_simple_SimpleData_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.incarcloud.grpc.proto.Simple.internal_static_simple_SimpleData_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.incarcloud.grpc.proto.Simple.SimpleData.class, com.incarcloud.grpc.proto.Simple.SimpleData.Builder.class);
    }

    public static final int LONGITUDE_FIELD_NUMBER = 1;
    private double longitude_;
    /**
     * <code>double longitude = 1;</code>
     * @return The longitude.
     */
    public double getLongitude() {
      return longitude_;
    }

    public static final int LATITUDE_FIELD_NUMBER = 2;
    private double latitude_;
    /**
     * <code>double latitude = 2;</code>
     * @return The latitude.
     */
    public double getLatitude() {
      return latitude_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (longitude_ != 0D) {
        output.writeDouble(1, longitude_);
      }
      if (latitude_ != 0D) {
        output.writeDouble(2, latitude_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (longitude_ != 0D) {
        size += com.google.protobuf.CodedOutputStream
          .computeDoubleSize(1, longitude_);
      }
      if (latitude_ != 0D) {
        size += com.google.protobuf.CodedOutputStream
          .computeDoubleSize(2, latitude_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.incarcloud.grpc.proto.Simple.SimpleData)) {
        return super.equals(obj);
      }
      com.incarcloud.grpc.proto.Simple.SimpleData other = (com.incarcloud.grpc.proto.Simple.SimpleData) obj;

      if (java.lang.Double.doubleToLongBits(getLongitude())
          != java.lang.Double.doubleToLongBits(
              other.getLongitude())) return false;
      if (java.lang.Double.doubleToLongBits(getLatitude())
          != java.lang.Double.doubleToLongBits(
              other.getLatitude())) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + LONGITUDE_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          java.lang.Double.doubleToLongBits(getLongitude()));
      hash = (37 * hash) + LATITUDE_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          java.lang.Double.doubleToLongBits(getLatitude()));
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.incarcloud.grpc.proto.Simple.SimpleData parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.incarcloud.grpc.proto.Simple.SimpleData parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.incarcloud.grpc.proto.Simple.SimpleData parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.incarcloud.grpc.proto.Simple.SimpleData parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.incarcloud.grpc.proto.Simple.SimpleData parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.incarcloud.grpc.proto.Simple.SimpleData parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.incarcloud.grpc.proto.Simple.SimpleData parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.incarcloud.grpc.proto.Simple.SimpleData parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.incarcloud.grpc.proto.Simple.SimpleData parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.incarcloud.grpc.proto.Simple.SimpleData parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.incarcloud.grpc.proto.Simple.SimpleData parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.incarcloud.grpc.proto.Simple.SimpleData parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.incarcloud.grpc.proto.Simple.SimpleData prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code simple.SimpleData}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:simple.SimpleData)
        com.incarcloud.grpc.proto.Simple.SimpleDataOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.incarcloud.grpc.proto.Simple.internal_static_simple_SimpleData_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.incarcloud.grpc.proto.Simple.internal_static_simple_SimpleData_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.incarcloud.grpc.proto.Simple.SimpleData.class, com.incarcloud.grpc.proto.Simple.SimpleData.Builder.class);
      }

      // Construct using com.incarcloud.grpc.proto.Simple.SimpleData.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        longitude_ = 0D;

        latitude_ = 0D;

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.incarcloud.grpc.proto.Simple.internal_static_simple_SimpleData_descriptor;
      }

      @java.lang.Override
      public com.incarcloud.grpc.proto.Simple.SimpleData getDefaultInstanceForType() {
        return com.incarcloud.grpc.proto.Simple.SimpleData.getDefaultInstance();
      }

      @java.lang.Override
      public com.incarcloud.grpc.proto.Simple.SimpleData build() {
        com.incarcloud.grpc.proto.Simple.SimpleData result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.incarcloud.grpc.proto.Simple.SimpleData buildPartial() {
        com.incarcloud.grpc.proto.Simple.SimpleData result = new com.incarcloud.grpc.proto.Simple.SimpleData(this);
        result.longitude_ = longitude_;
        result.latitude_ = latitude_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.incarcloud.grpc.proto.Simple.SimpleData) {
          return mergeFrom((com.incarcloud.grpc.proto.Simple.SimpleData)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.incarcloud.grpc.proto.Simple.SimpleData other) {
        if (other == com.incarcloud.grpc.proto.Simple.SimpleData.getDefaultInstance()) return this;
        if (other.getLongitude() != 0D) {
          setLongitude(other.getLongitude());
        }
        if (other.getLatitude() != 0D) {
          setLatitude(other.getLatitude());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.incarcloud.grpc.proto.Simple.SimpleData parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.incarcloud.grpc.proto.Simple.SimpleData) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private double longitude_ ;
      /**
       * <code>double longitude = 1;</code>
       * @return The longitude.
       */
      public double getLongitude() {
        return longitude_;
      }
      /**
       * <code>double longitude = 1;</code>
       * @param value The longitude to set.
       * @return This builder for chaining.
       */
      public Builder setLongitude(double value) {
        
        longitude_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>double longitude = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearLongitude() {
        
        longitude_ = 0D;
        onChanged();
        return this;
      }

      private double latitude_ ;
      /**
       * <code>double latitude = 2;</code>
       * @return The latitude.
       */
      public double getLatitude() {
        return latitude_;
      }
      /**
       * <code>double latitude = 2;</code>
       * @param value The latitude to set.
       * @return This builder for chaining.
       */
      public Builder setLatitude(double value) {
        
        latitude_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>double latitude = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearLatitude() {
        
        latitude_ = 0D;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:simple.SimpleData)
    }

    // @@protoc_insertion_point(class_scope:simple.SimpleData)
    private static final com.incarcloud.grpc.proto.Simple.SimpleData DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.incarcloud.grpc.proto.Simple.SimpleData();
    }

    public static com.incarcloud.grpc.proto.Simple.SimpleData getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<SimpleData>
        PARSER = new com.google.protobuf.AbstractParser<SimpleData>() {
      @java.lang.Override
      public SimpleData parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new SimpleData(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<SimpleData> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<SimpleData> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.incarcloud.grpc.proto.Simple.SimpleData getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface SimpleDataListOrBuilder extends
      // @@protoc_insertion_point(interface_extends:simple.SimpleDataList)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>repeated .simple.SimpleData simpleData = 1;</code>
     */
    java.util.List<com.incarcloud.grpc.proto.Simple.SimpleData> 
        getSimpleDataList();
    /**
     * <code>repeated .simple.SimpleData simpleData = 1;</code>
     */
    com.incarcloud.grpc.proto.Simple.SimpleData getSimpleData(int index);
    /**
     * <code>repeated .simple.SimpleData simpleData = 1;</code>
     */
    int getSimpleDataCount();
    /**
     * <code>repeated .simple.SimpleData simpleData = 1;</code>
     */
    java.util.List<? extends com.incarcloud.grpc.proto.Simple.SimpleDataOrBuilder> 
        getSimpleDataOrBuilderList();
    /**
     * <code>repeated .simple.SimpleData simpleData = 1;</code>
     */
    com.incarcloud.grpc.proto.Simple.SimpleDataOrBuilder getSimpleDataOrBuilder(
        int index);
  }
  /**
   * Protobuf type {@code simple.SimpleDataList}
   */
  public  static final class SimpleDataList extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:simple.SimpleDataList)
      SimpleDataListOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use SimpleDataList.newBuilder() to construct.
    private SimpleDataList(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private SimpleDataList() {
      simpleData_ = java.util.Collections.emptyList();
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new SimpleDataList();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private SimpleDataList(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              if (!((mutable_bitField0_ & 0x00000001) != 0)) {
                simpleData_ = new java.util.ArrayList<com.incarcloud.grpc.proto.Simple.SimpleData>();
                mutable_bitField0_ |= 0x00000001;
              }
              simpleData_.add(
                  input.readMessage(com.incarcloud.grpc.proto.Simple.SimpleData.parser(), extensionRegistry));
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000001) != 0)) {
          simpleData_ = java.util.Collections.unmodifiableList(simpleData_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.incarcloud.grpc.proto.Simple.internal_static_simple_SimpleDataList_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.incarcloud.grpc.proto.Simple.internal_static_simple_SimpleDataList_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.incarcloud.grpc.proto.Simple.SimpleDataList.class, com.incarcloud.grpc.proto.Simple.SimpleDataList.Builder.class);
    }

    public static final int SIMPLEDATA_FIELD_NUMBER = 1;
    private java.util.List<com.incarcloud.grpc.proto.Simple.SimpleData> simpleData_;
    /**
     * <code>repeated .simple.SimpleData simpleData = 1;</code>
     */
    public java.util.List<com.incarcloud.grpc.proto.Simple.SimpleData> getSimpleDataList() {
      return simpleData_;
    }
    /**
     * <code>repeated .simple.SimpleData simpleData = 1;</code>
     */
    public java.util.List<? extends com.incarcloud.grpc.proto.Simple.SimpleDataOrBuilder> 
        getSimpleDataOrBuilderList() {
      return simpleData_;
    }
    /**
     * <code>repeated .simple.SimpleData simpleData = 1;</code>
     */
    public int getSimpleDataCount() {
      return simpleData_.size();
    }
    /**
     * <code>repeated .simple.SimpleData simpleData = 1;</code>
     */
    public com.incarcloud.grpc.proto.Simple.SimpleData getSimpleData(int index) {
      return simpleData_.get(index);
    }
    /**
     * <code>repeated .simple.SimpleData simpleData = 1;</code>
     */
    public com.incarcloud.grpc.proto.Simple.SimpleDataOrBuilder getSimpleDataOrBuilder(
        int index) {
      return simpleData_.get(index);
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      for (int i = 0; i < simpleData_.size(); i++) {
        output.writeMessage(1, simpleData_.get(i));
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      for (int i = 0; i < simpleData_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, simpleData_.get(i));
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.incarcloud.grpc.proto.Simple.SimpleDataList)) {
        return super.equals(obj);
      }
      com.incarcloud.grpc.proto.Simple.SimpleDataList other = (com.incarcloud.grpc.proto.Simple.SimpleDataList) obj;

      if (!getSimpleDataList()
          .equals(other.getSimpleDataList())) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (getSimpleDataCount() > 0) {
        hash = (37 * hash) + SIMPLEDATA_FIELD_NUMBER;
        hash = (53 * hash) + getSimpleDataList().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.incarcloud.grpc.proto.Simple.SimpleDataList parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.incarcloud.grpc.proto.Simple.SimpleDataList parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.incarcloud.grpc.proto.Simple.SimpleDataList parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.incarcloud.grpc.proto.Simple.SimpleDataList parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.incarcloud.grpc.proto.Simple.SimpleDataList parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.incarcloud.grpc.proto.Simple.SimpleDataList parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.incarcloud.grpc.proto.Simple.SimpleDataList parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.incarcloud.grpc.proto.Simple.SimpleDataList parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.incarcloud.grpc.proto.Simple.SimpleDataList parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.incarcloud.grpc.proto.Simple.SimpleDataList parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.incarcloud.grpc.proto.Simple.SimpleDataList parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.incarcloud.grpc.proto.Simple.SimpleDataList parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.incarcloud.grpc.proto.Simple.SimpleDataList prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code simple.SimpleDataList}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:simple.SimpleDataList)
        com.incarcloud.grpc.proto.Simple.SimpleDataListOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.incarcloud.grpc.proto.Simple.internal_static_simple_SimpleDataList_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.incarcloud.grpc.proto.Simple.internal_static_simple_SimpleDataList_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.incarcloud.grpc.proto.Simple.SimpleDataList.class, com.incarcloud.grpc.proto.Simple.SimpleDataList.Builder.class);
      }

      // Construct using com.incarcloud.grpc.proto.Simple.SimpleDataList.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
          getSimpleDataFieldBuilder();
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        if (simpleDataBuilder_ == null) {
          simpleData_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
        } else {
          simpleDataBuilder_.clear();
        }
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.incarcloud.grpc.proto.Simple.internal_static_simple_SimpleDataList_descriptor;
      }

      @java.lang.Override
      public com.incarcloud.grpc.proto.Simple.SimpleDataList getDefaultInstanceForType() {
        return com.incarcloud.grpc.proto.Simple.SimpleDataList.getDefaultInstance();
      }

      @java.lang.Override
      public com.incarcloud.grpc.proto.Simple.SimpleDataList build() {
        com.incarcloud.grpc.proto.Simple.SimpleDataList result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.incarcloud.grpc.proto.Simple.SimpleDataList buildPartial() {
        com.incarcloud.grpc.proto.Simple.SimpleDataList result = new com.incarcloud.grpc.proto.Simple.SimpleDataList(this);
        int from_bitField0_ = bitField0_;
        if (simpleDataBuilder_ == null) {
          if (((bitField0_ & 0x00000001) != 0)) {
            simpleData_ = java.util.Collections.unmodifiableList(simpleData_);
            bitField0_ = (bitField0_ & ~0x00000001);
          }
          result.simpleData_ = simpleData_;
        } else {
          result.simpleData_ = simpleDataBuilder_.build();
        }
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.incarcloud.grpc.proto.Simple.SimpleDataList) {
          return mergeFrom((com.incarcloud.grpc.proto.Simple.SimpleDataList)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.incarcloud.grpc.proto.Simple.SimpleDataList other) {
        if (other == com.incarcloud.grpc.proto.Simple.SimpleDataList.getDefaultInstance()) return this;
        if (simpleDataBuilder_ == null) {
          if (!other.simpleData_.isEmpty()) {
            if (simpleData_.isEmpty()) {
              simpleData_ = other.simpleData_;
              bitField0_ = (bitField0_ & ~0x00000001);
            } else {
              ensureSimpleDataIsMutable();
              simpleData_.addAll(other.simpleData_);
            }
            onChanged();
          }
        } else {
          if (!other.simpleData_.isEmpty()) {
            if (simpleDataBuilder_.isEmpty()) {
              simpleDataBuilder_.dispose();
              simpleDataBuilder_ = null;
              simpleData_ = other.simpleData_;
              bitField0_ = (bitField0_ & ~0x00000001);
              simpleDataBuilder_ = 
                com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                   getSimpleDataFieldBuilder() : null;
            } else {
              simpleDataBuilder_.addAllMessages(other.simpleData_);
            }
          }
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.incarcloud.grpc.proto.Simple.SimpleDataList parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.incarcloud.grpc.proto.Simple.SimpleDataList) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.util.List<com.incarcloud.grpc.proto.Simple.SimpleData> simpleData_ =
        java.util.Collections.emptyList();
      private void ensureSimpleDataIsMutable() {
        if (!((bitField0_ & 0x00000001) != 0)) {
          simpleData_ = new java.util.ArrayList<com.incarcloud.grpc.proto.Simple.SimpleData>(simpleData_);
          bitField0_ |= 0x00000001;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilderV3<
          com.incarcloud.grpc.proto.Simple.SimpleData, com.incarcloud.grpc.proto.Simple.SimpleData.Builder, com.incarcloud.grpc.proto.Simple.SimpleDataOrBuilder> simpleDataBuilder_;

      /**
       * <code>repeated .simple.SimpleData simpleData = 1;</code>
       */
      public java.util.List<com.incarcloud.grpc.proto.Simple.SimpleData> getSimpleDataList() {
        if (simpleDataBuilder_ == null) {
          return java.util.Collections.unmodifiableList(simpleData_);
        } else {
          return simpleDataBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .simple.SimpleData simpleData = 1;</code>
       */
      public int getSimpleDataCount() {
        if (simpleDataBuilder_ == null) {
          return simpleData_.size();
        } else {
          return simpleDataBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .simple.SimpleData simpleData = 1;</code>
       */
      public com.incarcloud.grpc.proto.Simple.SimpleData getSimpleData(int index) {
        if (simpleDataBuilder_ == null) {
          return simpleData_.get(index);
        } else {
          return simpleDataBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .simple.SimpleData simpleData = 1;</code>
       */
      public Builder setSimpleData(
          int index, com.incarcloud.grpc.proto.Simple.SimpleData value) {
        if (simpleDataBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureSimpleDataIsMutable();
          simpleData_.set(index, value);
          onChanged();
        } else {
          simpleDataBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .simple.SimpleData simpleData = 1;</code>
       */
      public Builder setSimpleData(
          int index, com.incarcloud.grpc.proto.Simple.SimpleData.Builder builderForValue) {
        if (simpleDataBuilder_ == null) {
          ensureSimpleDataIsMutable();
          simpleData_.set(index, builderForValue.build());
          onChanged();
        } else {
          simpleDataBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .simple.SimpleData simpleData = 1;</code>
       */
      public Builder addSimpleData(com.incarcloud.grpc.proto.Simple.SimpleData value) {
        if (simpleDataBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureSimpleDataIsMutable();
          simpleData_.add(value);
          onChanged();
        } else {
          simpleDataBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .simple.SimpleData simpleData = 1;</code>
       */
      public Builder addSimpleData(
          int index, com.incarcloud.grpc.proto.Simple.SimpleData value) {
        if (simpleDataBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureSimpleDataIsMutable();
          simpleData_.add(index, value);
          onChanged();
        } else {
          simpleDataBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .simple.SimpleData simpleData = 1;</code>
       */
      public Builder addSimpleData(
          com.incarcloud.grpc.proto.Simple.SimpleData.Builder builderForValue) {
        if (simpleDataBuilder_ == null) {
          ensureSimpleDataIsMutable();
          simpleData_.add(builderForValue.build());
          onChanged();
        } else {
          simpleDataBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .simple.SimpleData simpleData = 1;</code>
       */
      public Builder addSimpleData(
          int index, com.incarcloud.grpc.proto.Simple.SimpleData.Builder builderForValue) {
        if (simpleDataBuilder_ == null) {
          ensureSimpleDataIsMutable();
          simpleData_.add(index, builderForValue.build());
          onChanged();
        } else {
          simpleDataBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .simple.SimpleData simpleData = 1;</code>
       */
      public Builder addAllSimpleData(
          java.lang.Iterable<? extends com.incarcloud.grpc.proto.Simple.SimpleData> values) {
        if (simpleDataBuilder_ == null) {
          ensureSimpleDataIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, simpleData_);
          onChanged();
        } else {
          simpleDataBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .simple.SimpleData simpleData = 1;</code>
       */
      public Builder clearSimpleData() {
        if (simpleDataBuilder_ == null) {
          simpleData_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
          onChanged();
        } else {
          simpleDataBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .simple.SimpleData simpleData = 1;</code>
       */
      public Builder removeSimpleData(int index) {
        if (simpleDataBuilder_ == null) {
          ensureSimpleDataIsMutable();
          simpleData_.remove(index);
          onChanged();
        } else {
          simpleDataBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .simple.SimpleData simpleData = 1;</code>
       */
      public com.incarcloud.grpc.proto.Simple.SimpleData.Builder getSimpleDataBuilder(
          int index) {
        return getSimpleDataFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .simple.SimpleData simpleData = 1;</code>
       */
      public com.incarcloud.grpc.proto.Simple.SimpleDataOrBuilder getSimpleDataOrBuilder(
          int index) {
        if (simpleDataBuilder_ == null) {
          return simpleData_.get(index);  } else {
          return simpleDataBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .simple.SimpleData simpleData = 1;</code>
       */
      public java.util.List<? extends com.incarcloud.grpc.proto.Simple.SimpleDataOrBuilder> 
           getSimpleDataOrBuilderList() {
        if (simpleDataBuilder_ != null) {
          return simpleDataBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(simpleData_);
        }
      }
      /**
       * <code>repeated .simple.SimpleData simpleData = 1;</code>
       */
      public com.incarcloud.grpc.proto.Simple.SimpleData.Builder addSimpleDataBuilder() {
        return getSimpleDataFieldBuilder().addBuilder(
            com.incarcloud.grpc.proto.Simple.SimpleData.getDefaultInstance());
      }
      /**
       * <code>repeated .simple.SimpleData simpleData = 1;</code>
       */
      public com.incarcloud.grpc.proto.Simple.SimpleData.Builder addSimpleDataBuilder(
          int index) {
        return getSimpleDataFieldBuilder().addBuilder(
            index, com.incarcloud.grpc.proto.Simple.SimpleData.getDefaultInstance());
      }
      /**
       * <code>repeated .simple.SimpleData simpleData = 1;</code>
       */
      public java.util.List<com.incarcloud.grpc.proto.Simple.SimpleData.Builder> 
           getSimpleDataBuilderList() {
        return getSimpleDataFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilderV3<
          com.incarcloud.grpc.proto.Simple.SimpleData, com.incarcloud.grpc.proto.Simple.SimpleData.Builder, com.incarcloud.grpc.proto.Simple.SimpleDataOrBuilder> 
          getSimpleDataFieldBuilder() {
        if (simpleDataBuilder_ == null) {
          simpleDataBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
              com.incarcloud.grpc.proto.Simple.SimpleData, com.incarcloud.grpc.proto.Simple.SimpleData.Builder, com.incarcloud.grpc.proto.Simple.SimpleDataOrBuilder>(
                  simpleData_,
                  ((bitField0_ & 0x00000001) != 0),
                  getParentForChildren(),
                  isClean());
          simpleData_ = null;
        }
        return simpleDataBuilder_;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:simple.SimpleDataList)
    }

    // @@protoc_insertion_point(class_scope:simple.SimpleDataList)
    private static final com.incarcloud.grpc.proto.Simple.SimpleDataList DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.incarcloud.grpc.proto.Simple.SimpleDataList();
    }

    public static com.incarcloud.grpc.proto.Simple.SimpleDataList getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<SimpleDataList>
        PARSER = new com.google.protobuf.AbstractParser<SimpleDataList>() {
      @java.lang.Override
      public SimpleDataList parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new SimpleDataList(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<SimpleDataList> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<SimpleDataList> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.incarcloud.grpc.proto.Simple.SimpleDataList getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_simple_SimpleParam_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_simple_SimpleParam_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_simple_SimpleData_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_simple_SimpleData_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_simple_SimpleDataList_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_simple_SimpleDataList_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\014Simple.proto\022\006simple\"\032\n\013SimpleParam\022\013\n" +
      "\003vin\030\001 \001(\t\"1\n\nSimpleData\022\021\n\tlongitude\030\001 " +
      "\001(\001\022\020\n\010latitude\030\002 \001(\001\"8\n\016SimpleDataList\022" +
      "&\n\nsimpleData\030\001 \003(\0132\022.simple.SimpleData2" +
      "I\n\rSimpleService\0228\n\tqueryList\022\023.simple.S" +
      "impleParam\032\026.simple.SimpleDataListB#\n\031co" +
      "m.incarcloud.grpc.protoB\006Simpleb\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_simple_SimpleParam_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_simple_SimpleParam_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_simple_SimpleParam_descriptor,
        new java.lang.String[] { "Vin", });
    internal_static_simple_SimpleData_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_simple_SimpleData_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_simple_SimpleData_descriptor,
        new java.lang.String[] { "Longitude", "Latitude", });
    internal_static_simple_SimpleDataList_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_simple_SimpleDataList_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_simple_SimpleDataList_descriptor,
        new java.lang.String[] { "SimpleData", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
